# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=32, unique=True, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='HotelCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_name', models.CharField(blank=True, max_length=32, unique=True, verbose_name='name')),
                ('hc_description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('hc_title_img', models.ImageField(blank=True, upload_to='media', verbose_name='title_img')),
            ],
        ),
        migrations.CreateModel(
            name='HotelDateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='check-in')),
                ('checkout', models.DateField(verbose_name='check-out')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_places', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='places')),
                ('hr_description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('hr_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('hr_title_img', models.ImageField(blank=True, upload_to='media', verbose_name='title_img')),
                ('hr_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.Category')),
                ('hr_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.HotelCard')),
            ],
        ),
        migrations.AddField(
            model_name='hoteldaterange',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.HotelRoom'),
        ),
    ]
